### ISSUE TITLE
V1.1 Release Checklist

### ISSUE THREAD

**Issue by ilikeprograms** [ilikeprograms/Cluckles#15]
Here is a full list of ideas/features I want to support by the release of V.1.1.
- [ ] Add Font importing support, to the Editor/Docs can import custom fonts to view them before exporting the font definitions
- [ ] Add support for displaying different values for Color inputs in the Inputs (switch between RGB/Hex etc)
- [ ] Add Introduction/Tutorial to the Docs site
- [ ] Rework the Main Editor/Sidebar positioning/scrollbar

If anyone wants to help out and add support for any of these parts then feel free to submit a pull request, or create issues for anything which you feel needs to be in v.1.1!
